module.exports = {
    "aud_1_1_1": "Responsable del SG-SST",
    "aud_1_1_2": "Responsabilidades en el SG-SST",
    "aud_1_1_3": "Asignación de recursos para el SG-SST",
    "aud_1_1_4": "Afiliación al Sistema General de Riesgos Laborales",
    "aud_1_1_5": "Pago de pensión de trabajadores de alto riesgo",
    "aud_1_1_6": "Conformación del COPASST",
    "aud_1_1_6_riesgos": " > Validación Matriz de Riesgos",
    "aud_1_1_6_at": " > Investigación de Accidentes",
    "aud_1_1_6_inspecciones": " > Informes de Inspección",
    "aud_1_1_6_cambio": " > Gestión del Cambio",
    "aud_1_1_6_auditoria": " > Auditoría Anual",
    "aud_1_1_7": "Capacitación del COPASST",
    "aud_1_1_7_investigacion": " > Inv. Accidentes (Metodología)",
    "aud_1_1_7_inspecciones": " > Inspecciones de Seguridad",
    "aud_1_1_7_peligros": " > Identificación de Peligros",
    "aud_1_1_7_funciones": " > Funciones y Responsabilidades",
    "aud_1_1_8": "Conformación del Comité de Convivencia (Actualizado 2025)",
    "aud_1_1_8_normativa": " > Nuevo Marco Normativo",
    "aud_1_1_8_acoso": " > Acoso Laboral",
    "aud_1_1_8_conflictos": " > Resolución de Conflictos",
    "aud_1_1_8_sexual": " > Acoso Sexual",
    "aud_1_1_8_psicosocial": " > Sensibilización Riesgo Psicosocial",
    "aud_1_1_8_etica": " > Ética y Confidencialidad",
    "aud_ley_2365": "Prevención Acoso Sexual",
    "aud_1_2_1": "Programa de capacitación en promoción y prevención",
    "aud_1_2_2": "Capacitación, inducción y reinducción en SG-SST",
    "aud_1_2_3": "Responsables del SG-SST con curso virtual de 50 horas",
    "aud_2_1_1": "Política del SG-SST firmada, fechada y comunicada",
    "aud_pol_spa": "Política de Prevención de Consumo de SPA",
    "aud_pol_acoso": "Política de Prevención del Acoso Laboral",
    "aud_pol_vial": "Política de Seguridad Vial",
    "aud_pol_datos": "Política de Tratamiento de Datos Personales",
    "aud_ley_2191": "Política de Desconexión Laboral",
    "aud_pol_mental": "Política de Salud Mental y Bienestar",
    "aud_2_2_1": "Objetivos definidos, claros, medibles y cuantificables",
    "aud_2_3_1": "Evaluación inicial del SG-SST e identificación de prioridades",
    "aud_2_4_1": "Plan de trabajo anual",
    "aud_2_5_1": "Archivo y retención documental del SG-SST",
    "aud_2_6_1": "Rendición de cuentas sobre el desempeño",
    "aud_2_7_1": "Matriz legal actualizada",
    "aud_2_8_1": "Mecanismos de comunicación interna y externa",
    "aud_2_9_1": "Procedimiento de adquisiciones con criterios de SST",
    "aud_2_10_1": "Evaluación y selección de contratistas y proveedores",
    "aud_2_11_1": "Evaluación del impacto de cambios internos y externos",
    "aud_reg_higiene": "Reglamento de Higiene y Seguridad Industrial",
    "aud_reg_rit": "Reglamento Interno de Trabajo (RIT)",
    "aud_3_1_1": "Descripción sociodemográfica y Diagnóstico de condiciones de salud",
    "aud_3_1_2": "Actividades de promoción y prevención en salud",
    "aud_3_1_3": "Información al médico de perfiles de cargo",
    "aud_3_1_4": "Realización de evaluaciones médicas",
    "aud_3_1_5": "Custodia de historias clínicas",
    "aud_3_1_6": "Restricciones y recomendaciones médicas",
    "aud_3_1_7": "Estilos de vida y entornos de trabajo saludable",
    "aud_3_1_8": "Agua potable, servicios sanitarios y disposición de basuras",
    "aud_3_1_9": "Eliminación adecuada de residuos",
    "aud_3_2_1": "Reporte de accidentes de trabajo a la ARL",
    "aud_3_2_2": "Investigación de accidentes, incidentes y enfermedades",
    "aud_3_2_3": "Registro y análisis estadístico de ATEL",
    "aud_3_3_1": "Medición de la severidad de los AT",
    "aud_3_3_2": "Medición de la frecuencia de los AT",
    "aud_3_3_3": "Medición de la mortalidad por AT",
    "aud_3_3_4": "Medición de la prevalencia de la EL",
    "aud_3_3_5": "Medición de la incidencia de la EL",
    "aud_3_3_6": "Medición del ausentismo por causa médica",
    "aud_4_1_1": "Metodología para identificación de peligros y evaluación de riesgos",
    "aud_4_1_2": "Identificación de peligros con participación de trabajadores",
    "aud_4_1_3": "Identificación de sustancias catalogadas como carcinógenas o con toxicidad aguda",
    "aud_4_1_4": "Realización de mediciones ambientales, químicos, físicos y biológicos",
    "aud_4_2_1": "Implementación de medidas de prevención y control",
    "aud_res_2764": "Riesgo Psicosocial",
    "aud_ley_2050": "Seguridad Vial (PESV)",
    "aud_sga": "SGA - Productos Químicos",
    "aud_alturas": "Trabajo en Alturas",
    "aud_confinados": "Espacios Confinados",
    "aud_4_2_2": "Verificación de medidas de prevención y control",
    "aud_4_2_3": "Elaboración de procedimientos, instructivos y fichas técnicas",
    "aud_4_2_4": "Inspecciones de seguridad",
    "aud_4_2_5": "Mantenimiento periódico de instalaciones y equipos",
    "aud_4_2_6": "Entrega de EPP y capacitación en uso",
    "aud_5_1_1": "Plan de prevención, preparación y respuesta ante emergencias",
    "aud_5_1_2": "Brigada de prevención, preparación y respuesta ante emergencias",
    "aud_6_1_1": "Definición de indicadores del SG-SST",
    "aud_6_1_2": "Auditoría anual",
    "aud_6_1_3": "Revisión por la alta dirección",
    "aud_6_1_4": "Planificación auditorías con el COPASST",
    "aud_7_1_1": "Acciones preventivas y correctivas con base en resultados",
    "aud_7_1_2": "Acciones de mejora según revisión de la alta dirección",
    "aud_7_1_3": "Acciones de mejora basadas en investigaciones de ATEL",
    "aud_7_1_4": "Plan de mejoramiento continuo"
};
